### ISSUE TITLE
InvalidCastException when cloning a method with switch cases

### ISSUE THREAD

**Issue by FakeDomi** [snaphat/MonoCecilExtensions#1]
Patching a .NET Framework 4.8 assembly, if that matters.
MonoCecilExtensions: master
Mono.Cecil: 0.11.6

The following method causes an exception when cloning.

```cs
public override void WriteLine(string value)
{
    if (value == null)
    {
        base.WriteLine();
        return;
    }

    StringBuilder line = new StringBuilder(value.Length);

    foreach (char c in value)
    {
        switch (c)
        {
            case (char)0x00: // NUL
            case (char)0x01: // SOH
            case (char)0x02: // STX
            case (char)0x03: // ETX
            case (char)0x04: // EOT
            case (char)0x05: // ENQ
            case (char)0x06: // ACK
            case (char)0x07: // BEL
            case (char)0x08: // BS
            case (char)0x09: // HT
            case (char)0x0B: // VT
            case (char)0x0C: // FF
            case (char)0x0E: // SO
            case (char)0x0F: // SI
            case (char)0x10: // DLE
            case (char)0x11: // DC1
            case (char)0x12: // DC2
            case (char)0x13: // DC3
            case (char)0x14: // DC4
            case (char)0x15: // NAK
            case (char)0x16: // SYN
            case (char)0x17: // ETB
            case (char)0x18: // CAN
            case (char)0x19: // EM
            case (char)0x1A: // SUB
            case (char)0x1B: // ESC
            case (char)0x1C: // FS
            case (char)0x1D: // GS
            case (char)0x1E: // RS
            case (char)0x1F: // US
            case (char)0x7F: // DEL
                line.Append(' ');
                break;
            default:
                line.Append(c);
                break;
        }
    }

    base.WriteLine(line.ToString());
}
```

```
System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.Cil.Instruction[]' to type 'Mono.Cecil.Cil.Instruction'.
   at MonoCecilExtensions.Clone(MethodDefinition method) in C:\Repos\Test\MonoCecilExtensions.cs:line 656
   at MonoCecilExtensions.AddFieldsPropertiesAndMethods(TypeDefinition dest, TypeDefinition src) in C:\Repos\Test\MonoCecilExtensions.cs:line 282
   at MonoCecilExtensions.AddType(AssemblyDefinition assembly, TypeDefinition src, Boolean avoidSignatureConflicts) in C:\Repos\Test\MonoCecilExtensions.cs:line 219
   at Test.Program.Patch(String path) in C:\Repos\Test\Program.cs:line 57
   at Test.Program.Main(String[] args) in C:\Repos\Test\Program.cs:line 36
```

The fix seems to be adding an `instruction.Operand is Instruction` check before line 656 (It's what I did and it works fine).
There's code specifically for switches below so it looks like you're not even meant to end up in that block.

Also, thanks for this useful library!

**Comment by snaphat** [comment]
Thanks! 

Your fix was absolutely correct! However, I realized my handling of branches versus cases during cloning was disjointed and suboptimal which lead to the issue in the first place. To address this, I restructured the implementation based on how Mono.Cecil.Cil differentiates them in its [CodeWriter.cs](https://github.com/jbevain/cecil/blob/5de7d8cbc91f6fd98dcc24b26b8c398db497809c/Mono.Cecil.Cil/CodeWriter.cs#L396).

Since your bug report indicates someone is actively using this code, I also took the opportunity to improve the [documentation](https://github.com/snaphat/MonoCecilExtensions?tab=readme-ov-file#monocecilextensions), add a brief [example](https://github.com/snaphat/MonoCecilExtensions/tree/main/example) showcasing how to use some of the APIs, and include an [extension method](https://github.com/snaphat/MonoCecilExtensions?tab=readme-ov-file#clonecollectioninstruction) for cloning `Instruction` collections.

FYI: In case you didn’t notice, the code is public domain, so you’re free to incorporate it anywhere without attribution or restrictions.
